### ISSUE TITLE
Build error with node 12.8.1

### ISSUE THREAD

**Issue by HansVanEijsden** [mrene/node-minidsp#10]
Hi there,

I would like to build `node-minidsp` with `node 12.8.1` (the default in Homebrew), but it gives an error. Am I doing something wrong?

Here's the log:

```
$ npm install -g node-minidsp
/usr/local/bin/minidsp -> /usr/local/lib/node_modules/minidsp/minidsp.js

> get-cursor-position@1.0.3 install /Users/hans/node-minidsp/node_modules/get-cursor-position
> node-gyp rebuild

  CXX(target) Release/obj.target/pos/src/pos.o
../src/pos.cc:272:22: warning: 'NewFromUtf8' is deprecated: Use maybe version [-Wdeprecated-declarations]
    pos->Set(String::NewFromUtf8(isolate, "row"), Number::New(isolate, row));
                     ^
/Users/hans/Library/Caches/node-gyp/12.8.1/include/node/v8.h:2897:10: note: 'NewFromUtf8' has been explicitly marked deprecated here
  static V8_DEPRECATED(
         ^
/Users/hans/Library/Caches/node-gyp/12.8.1/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/pos.cc:272:10: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    pos->Set(String::NewFromUtf8(isolate, "row"), Number::New(isolate, row));
         ^
/Users/hans/Library/Caches/node-gyp/12.8.1/include/node/v8.h:3365:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/hans/Library/Caches/node-gyp/12.8.1/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../src/pos.cc:273:22: warning: 'NewFromUtf8' is deprecated: Use maybe version [-Wdeprecated-declarations]
    pos->Set(String::NewFromUtf8(isolate, "col"), Number::New(isolate, col));
                     ^
/Users/hans/Library/Caches/node-gyp/12.8.1/include/node/v8.h:2897:10: note: 'NewFromUtf8' has been explicitly marked deprecated here
  static V8_DEPRECATED(
         ^
/Users/hans/Library/Caches/node-gyp/12.8.1/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/pos.cc:273:10: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    pos->Set(String::NewFromUtf8(isolate, "col"), Number::New(isolate, col));
         ^
/Users/hans/Library/Caches/node-gyp/12.8.1/include/node/v8.h:3365:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/hans/Library/Caches/node-gyp/12.8.1/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../src/pos.cc:277:6: error: variable has incomplete type 'void'
void Init(Handle<Object> exports) {
     ^
../src/pos.cc:277:11: error: use of undeclared identifier 'Handle'
void Init(Handle<Object> exports) {
          ^
../src/pos.cc:277:18: error: 'Object' does not refer to a value
void Init(Handle<Object> exports) {
                 ^
/Users/hans/Library/Caches/node-gyp/12.8.1/include/node/v8.h:3363:17: note: declared here
class V8_EXPORT Object : public Value {
                ^
../src/pos.cc:277:26: error: use of undeclared identifier 'exports'
void Init(Handle<Object> exports) {
                         ^
../src/pos.cc:277:34: error: expected ';' after top level declarator
void Init(Handle<Object> exports) {
                                 ^
                                 ;
4 warnings and 5 errors generated.
make: *** [Release/obj.target/pos/src/pos.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/Cellar/node/12.8.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/hans/node-minidsp/node_modules/get-cursor-position
gyp ERR! node -v v12.8.1
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
npm WARN rollback Rolling back get-cursor-position@1.0.3 failed (this is probably harmless): /Users/hans/node-minidsp/node_modules/get-cursor-position is not a child of /usr/local/lib
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! get-cursor-position@1.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the get-cursor-position@1.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hans/.npm/_logs/2019-08-17T17_43_36_178Z-debug.log
```

I've attached the complete debug.log to this message. Thanks.
[debug.log.txt](https://github.com/mrene/node-minidsp/files/3512270/debug.log.txt)

**Comment by mrene** [comment]
It appears one of the indirect dependencies does not compile under 12.8.1 yet - I'd recommend using https://github.com/tj/n and using the LTS version of node (10.16.3) instead. 

Alternatively you could remove `ascii-progress` as a dependency from `package.json` - only the `monitor` command will be affected.

**Comment by HansVanEijsden** [comment]
Oh wow, `n` is brilliant. I didn't know about it. 👍🏻 It's up & running again. Thank you!
