### ISSUE TITLE
Error: Could not locate the bindings file.

### ISSUE THREAD

**Issue by Sturmkater** [mrene/node-minidsp#12]
Hi, running the module brings out this response:
`minidsp gain 0                            Mi 03 Mär 2021 08:49:14
/usr/local/lib/node_modules/minidsp/node_modules/bindings/bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/minidsp/node_modules/node-hid/build/HID-hidraw.node
 → /usr/local/lib/node_modules/minidsp/node_modules/node-hid/build/Debug/HID-hidraw.node
 → /usr/local/lib/node_modules/minidsp/node_modules/node-hid/build/Release/HID-hidraw.node
 → /usr/local/lib/node_modules/minidsp/node_modules/node-hid/out/Debug/HID-hidraw.node
 → /usr/local/lib/node_modules/minidsp/node_modules/node-hid/Debug/HID-hidraw.node
 → /usr/local/lib/node_modules/minidsp/node_modules/node-hid/out/Release/HID-hidraw.node
 → /usr/local/lib/node_modules/minidsp/node_modules/node-hid/Release/HID-hidraw.node
 → /usr/local/lib/node_modules/minidsp/node_modules/node-hid/build/default/HID-hidraw.node
 → /usr/local/lib/node_modules/minidsp/node_modules/node-hid/compiled/12.18.2/linux/x64/HID-hidraw.node
 → /usr/local/lib/node_modules/minidsp/node_modules/node-hid/addon-build/release/install-root/HID-hidraw.node
 → /usr/local/lib/node_modules/minidsp/node_modules/node-hid/addon-build/debug/install-root/HID-hidraw.node
 → /usr/local/lib/node_modules/minidsp/node_modules/node-hid/addon-build/default/install-root/HID-hidraw.node
 → /usr/local/lib/node_modules/minidsp/node_modules/node-hid/lib/binding/node-v72-linux-x64/HID-hidraw.node
    at bindings (/usr/local/lib/node_modules/minidsp/node_modules/bindings/bindings.js:126:9)
    at loadBinding (/usr/local/lib/node_modules/minidsp/node_modules/node-hid/nodehid.js:19:46)
    at new HID (/usr/local/lib/node_modules/minidsp/node_modules/node-hid/nodehid.js:35:5)
    at new USBTransport (/usr/local/lib/node_modules/minidsp/src/transport/usb.js:15:27)
    at device (/usr/local/lib/node_modules/minidsp/minidsp.js:57:43)
    at Command.<anonymous> (/usr/local/lib/node_modules/minidsp/minidsp.js:99:13)
    at Command.listener (/usr/local/lib/node_modules/minidsp/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:315:20)
    at Command.parseArgs (/usr/local/lib/node_modules/minidsp/node_modules/commander/index.js:651:12)
    at Command.parse (/usr/local/lib/node_modules/minidsp/node_modules/commander/index.js:474:21) {
  tries: [
    '/usr/local/lib/node_modules/minidsp/node_modules/node-hid/build/HID-hidraw.node',
    '/usr/local/lib/node_modules/minidsp/node_modules/node-hid/build/Debug/HID-hidraw.node',
    '/usr/local/lib/node_modules/minidsp/node_modules/node-hid/build/Release/HID-hidraw.node',
    '/usr/local/lib/node_modules/minidsp/node_modules/node-hid/out/Debug/HID-hidraw.node',
    '/usr/local/lib/node_modules/minidsp/node_modules/node-hid/Debug/HID-hidraw.node',
    '/usr/local/lib/node_modules/minidsp/node_modules/node-hid/out/Release/HID-hidraw.node',
    '/usr/local/lib/node_modules/minidsp/node_modules/node-hid/Release/HID-hidraw.node',
    '/usr/local/lib/node_modules/minidsp/node_modules/node-hid/build/default/HID-hidraw.node',
    '/usr/local/lib/node_modules/minidsp/node_modules/node-hid/compiled/12.18.2/linux/x64/HID-hidraw.node',
    '/usr/local/lib/node_modules/minidsp/node_modules/node-hid/addon-build/release/install-root/HID-hidraw.node',
    '/usr/local/lib/node_modules/minidsp/node_modules/node-hid/addon-build/debug/install-root/HID-hidraw.node',
    '/usr/local/lib/node_modules/minidsp/node_modules/node-hid/addon-build/default/install-root/HID-hidraw.node',
    '/usr/local/lib/node_modules/minidsp/node_modules/node-hid/lib/binding/node-v72-linux-x64/HID-hidraw.node'
  ]
}
`

Im on the most resent pop os 20.10 (ubuntu based), nodejs is installed (nodejs is already the newest version (12.18.2~dfsg-1ubuntu2)
Any idea what Im doing wrong? Thanks:-)

**Comment by mrene** [comment]
My guess would be that the HID library might not work with the most recent node version, or that you need the right packages to build them.

If you aren't trying to use this in your own node programs, may I suggest the newer [minidsp-rs](https://github.com/mrene/minidsp-rs/releases) project? It has pre-built packages that don't require building anything.

**Comment by Sturmkater** [comment]
Thanks, yea now it works like charm. minidsp-rs don't have your nice gain meters, but I will survive:-D Thaks again
